// SEARCH
export const TOGGLE_FILTER = 'TOGGLE_FILTER';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const TOGGLE_SAVED_SEARCH = 'TOGGLE_SAVED_SEARCH';
export const TOGGLE_SHOW_FAVORITES = 'TOGGLE_SHOW_FAVORITES';
export const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM';
export const ADD_STATUS_FILTER = 'ADD_STATUS_FILTER';
export const ADD_CONTENT_TYPE_FILTER = 'ADD_CONTENT_TYPE_FILTER';
export const ADD_TOPIC_FILTER = 'ADD_TOPIC_FILTER';
export const REMOVE_STATUS_FILTER = 'REMOVE_STATUS_FILTER';
export const REMOVE_CONTENT_TYPE_FILTER = 'REMOVE_CONTENT_TYPE_FILTER';
export const REMOVE_TOPIC_FILTER = 'REMOVE_TOPIC_FILTER';